apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recorded-future

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - cronjob.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: recorded-future
